export { default as PanelMain } from './PanelMain'
export { default as PanelDuo } from './PanelDuo'
export { default as PanelLeft } from './PanelLeft'
export { default as PanelEnd } from './PanelEnd'
export { default as PanelTitle } from './PanelTitle'
