export { default as PagePortfolios } from './PagePortfolios'
export { default as PagePfDesigns } from './PagePfDesigns'
export { default as PagePfProdutos } from './PagePfProdutos'
export { default as PagePfServicos } from './PagePfServicos'
export { default as PageDesignProd } from './PageDesignProd'
